version: "3"
services:
  dll-filebeat:
      image: docker.elastic.co/beats/filebeat:7.1.1
      volumes:
        - ./conf/filebeat.yml:/usr/share/filebeat/filebeat.yml
        - ./log:/tmp
         # needed to access all docker logs (read only) :
        - "/var/lib/docker/containers:/usr/share/dockerlogs/data:ro"
      # needed to access additional informations about containers
        - "/var/run/docker.sock:/var/run/docker.sock"
      container_name: dll-filebeat
      hostname: dll-filebeat
      restart: always
      privileged: true
      external_links:
        - dll-elasticsearch:dll-elasticsearch  #外部容器连接
      networks:
        - es-single_elk
networks:
  es-single_elk:
    external: true  